---
- name: kadai2_test
  hosts: cisco
  gather_facts: no
  become: yes
  become_method: enable
  vars:
    now_date: "{{ lookup('pipe','date +%Y%m%d%H%M')}}"


  tasks:
    - name: configure loopback settings
      cisco.ios.ios_config:
        lines:
        - ip address 100.0.0.1 255.255.255.255
        parents: interface loopback1

    - name: ospf config
      cisco.ios.ios_config:
        lines:
        - network 100.0.0.1 0.0.0.0 area 0
        parents: router ospf 1

    - name: gather router facts
      cisco.ios.ios_command:
        commands:
        - show ip route
      register: result

    - name: create directory on control node
      file:
        path: /home/student14/network-workshop/kadai2-files
        state: directory

    - copy:
        content: "{{ result.stdout[0] }}"
        dest: "./kadai2-files/{{ inventory_hostname }}_{{ now_date }}_result_route.txt"
